export const Makes = [
  { key: "alfa-romeo", label: "Alfa Romeo" },
  { key: "aston-martin", label: "Aston Martin" },
  { key: "audi", label: "Audi" },
  { key: "austin", label: "Austin" },
  { key: "bmw", label: "BMW" },
  { key: "buick", label: "Buick" },
  { key: "cadillac", label: "Cadillac" },
  { key: "changan", label: "Changan" },
  { key: "chery", label: "Chery" },
  { key: "chevrolet", label: "Chevrolet" },
  { key: "chrysler", label: "Chrysler" },
  { key: "citroen", label: "Citroen" },
  { key: "daewoo", label: "Daewoo" },
  { key: "daihatsu", label: "Daihatsu" },
  { key: "datsun", label: "Datsun" },
  { key: "dfsk", label: "DFSK" },
  { key: "dodge", label: "Dodge" },
  { key: "ferrari", label: "Ferrari" },
  { key: "fiat", label: "Fiat" },
  { key: "ford", label: "Ford" },
  { key: "geely", label: "Geely" },
  { key: "gmc", label: "GMC" },
  { key: "hino", label: "Hino" },
  { key: "honda", label: "Honda" },
  { key: "hummer", label: "Hummer" },
  { key: "hyundai", label: "Hyundai" },
  { key: "isuzu", label: "Isuzu" },
  { key: "jaguar", label: "Jaguar" },
  { key: "jeep", label: "Jeep" },
  { key: "kia", label: "Kia" },
  { key: "lamborghini", label: "Lamborghini" },
  { key: "land-rover", label: "Land Rover" },
  { key: "lexus", label: "Lexus" },
  { key: "lincoln", label: "Lincoln" },
  { key: "mahindra", label: "Mahindra" },
  { key: "maruti-suzuki", label: "Maruti Suzuki" },
  { key: "maruti", label: "Maruti" },
  { key: "mazda", label: "Mazda" },
  { key: "mercedes-benz", label: "Mercedes Benz" },
  { key: "mg", label: "MG" },
  { key: "micro", label: "Micro" },
  { key: "mini", label: "Mini" },
  { key: "mitsubishi", label: "Mitsubishi" },
  { key: "morris", label: "Morris" },
  { key: "moto-guzzi", label: "Moto Guzzi" },
  { key: "nissan", label: "Nissan" },
  { key: "oldsmobile", label: "Oldsmobile" },
  { key: "opel", label: "Opel" },
  { key: "other", label: "Other brand" },
  { key: "perodua", label: "Perodua" },
  { key: "peugeot", label: "Peugeot" },
  { key: "plymoth", label: "Plymoth" },
  { key: "pontiac", label: "Pontiac" },
  { key: "porsche", label: "Porsche" },
  { key: "proton", label: "Proton" },
  { key: "renault", label: "Renault" },
  { key: "rover", label: "Rover" },
  { key: "royal-enfield", label: "Royal Enfield" },
  { key: "saab", label: "Saab" },
  { key: "scion", label: "Scion" },
  { key: "seat", label: "SEAT" },
  { key: "skoda", label: "Skoda" },
  { key: "smart", label: "Smart" },
  { key: "ssang-yong", label: "Ssang Yong" },
  { key: "subaru", label: "Subaru" },
  { key: "suzuki", label: "Suzuki" },
  { key: "tata", label: "Tata" },
  { key: "tesla", label: "Tesla" },
  { key: "toyota", label: "Toyota" },
  { key: "vauxhall", label: "Vauxhall" },
  { key: "volkswagen", label: "Volkswagen" },
  { key: "volvo", label: "Volvo" },
  { key: "zotye", label: "Zotye" },
];
